cat > netlify.toml << 'EOF'
[build]
  publish = "build"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "create-react-app"
  command = "npm start"
  targetPort = 3000
  port = 8888
  publish = "build"
  autoLaunch = true
EOF